site_name: Monacs
site_url: https://monacslib.github.io/
site_description: Documentation for Monacs - A collection of basic monads and functional extensions for C#

repo_url: https://github.com/MonacsLib/Monacs
edit_uri: ""

pages:
  - Index: index.md
  - Quick Start: quickstart.md
  - Components:
    - Option: option.md
    - Result: result.md
    - ErrorDetails: errors.md
    - Unit: unit.md
  - Glossary: glossary.md
  - API docs: apidoc.md

theme: readthedocs
